### PR TITLE
JENKINS-27498 Handling an empty array of applications returned

### PR DESCRIPTION
**Pull request by sitUboo**
Attempting to address exception:
 org.jenkinsci.plugins.fodupload.FodUploaderPlugin$DescriptorImpl.loadPluginOptions(FodUploaderPlugin.java:496)
at org.jenkinsci.plugins.fodupload.FodUploaderPlugin$DescriptorImpl.configure(FodUploaderPlugin.java:307)
at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:3642)

### CODE REVIEW

**Comment by mtgibbs** [comment]
Hey thanks!

While this fixes the exception, does it behave nicely in the dropdown or send an error that no applications could be found?  Perhaps we should build that in as well.

**Comment by mtgibbs** [comment]
Alright thanks.  I'm on holiday right now, but I'll take a look at it as soon as I'm back.  I went ahead and took in the PR and we'll touch up what we need to for a better experience.

**Comment by kmadel** [comment]
When do we expect a release for this merge?

**Comment by mtgibbs** [comment]
I've got one other issue to handle with when there are blank values and saving, then I will release.

**Comment by mtgibbs** [comment]
Alright, this PR should be published.  Thanks again.

**Pull request merged**
