### PR TITLE
Adds support for jsx,ts, and tsx files as constant files

### LINKED ISSUE #98: TSX Support
Hi there!

Would you be open to including .tsx files in the constants list to be sent with any of the tech stacks using the constants files?

Fortify claims to support scanning tsx (and probably jsx) in their other tech stacks as "constants".

Happy to make a PR!

### PR DESCRIPTION
**Pull request by maly7**
fixes #98

### CODE REVIEW

**Comment by m0ps** [comment]
Hi @maly7!
I believe that js/jsx/ts/tsx should be a part of JS/TS/HTML tech stack that actually missed in the plugin code, but  mentioned in the documentation here: https://www.microfocus.com/documentation/fortify-on-demand-jenkins-plugin/5.0/FoD_Jenkins_Plugin_Help_5.0.0/index.htm#Running_Asmnts/Static/StaticPrep/SP_JS_HTML_XML.htm?Highlight=js/ts/html

**Comment by m0ps** [comment]
@timsotack ^^

**Comment by maly7** [comment]
Thanks, @m0ps! I'd be happy to update my PR with that clarification.

**Comment by kel00s** [comment]
I think you should add and update case condition accordingly with files extensions instead of update constant which is added to each tech stack type.

 private static final String TS_JS_TS_HTML = "JS/TS/HTML";

**Comment by maly7** [comment]
@kel00s I agree. According to the docs:
> JS/TS/HTML is a catch-all option for simple web applications and web applications that primarily use JavaScript-related technologies.
This implies that using the constants here should suffice as long as they're updated to include typescript files.

**Comment by kel00s** [comment]
I have some concerns here, If I want to upload the JS/TS code and don't have option to provide tech stack "JS/TS/HTML" as a parameter, this will cause that Java stack is used as default. 
Upload Java application requires at least one .jar file to be present.

**Comment by maly7** [comment]
@kel00s I added the separate tech stack for "JS/TS/HTML" which includes all JS/TS code. I've also added them to the constants, because according to the documentation the other tech stacks also support uploading of JS/TS code in their payload. This should enable uploading of JS/TS code by itself or with the other tech stacks.

**Comment by m0ps** [comment]
@timsotack, could you please take a look into the issue, that this PR is going to resolve?

**Comment by timsotack** [comment]
These extensions have been added in 3ab3a91eb850394496cd9c4e1cbfe4f386519048

**Pull request closed without merging**
