### PR TITLE
Changing the SSL context to use TLSv1.2 protocol as that's the only one supported by hpfod.com. This will specifically benefit teams running on older versions of Java 7 or 6.

### PR DESCRIPTION
**Pull request by pankajagarwal**

### CODE REVIEW

**Comment by mtgibbs** [comment]
Thanks for your PR!  We'll get it reviewed and taken in.

**Comment by timsotack** [comment]
It seems like you should be able to specify using TLS1.2 without having to access the keystore. Is there a reason not to use sslContext.init(null,null,null)? My understanding is that this will use the defaults for each parameter. Hardcoding the default password for the keystore is undesirable since it will fail if anyone changed it.

**Comment by pankajagarwal** [comment]
Feel free to try. With null for all three it was expecting keystore and keystore password as variables to be passed to jvm

**Comment by mtgibbs** [comment]
With the default password being specified, it seems like this would break existing users on Java 8 that do not use the default "changeit" password.  Your suggestion for passing these as variables to the JVM appears to be the most flexible for all users as it affords them more control.

**Comment by mtgibbs** [comment]
Plugin no longer supports anything below Java 8.

**Pull request closed without merging**
